version: '3.8'

services:
  symfony:
    build:
      context: .
      dockerfile: Dockerfile.symfony
    container_name: symfony-web
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    restart: always

  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    ports:
      - "5433:5432"
    restart: always
